### PR TITLE
Create options.optimizeKey to fit width around one column

### PR DESCRIPTION
**Pull request by HaraldNordgren**
See main discussion here: https://github.com/heroku/heroku-apps/pull/216

This is a fix that lays the groundwork for what I think is needed to fix the issue with terminal width adjustment problems.

### CODE REVIEW

**Comment by jdxcode** [comment]
thanks for working on this and I apologize that we're pretty behind with our work right now so we may not be able to work on this that much. I don't feel I fully understand the issue here that optimizeKey is supposed to solve. Also, we're moving this logic (very slowly) to cli-ux, so that project will eventually have to retain any new behavior.

I think what I'd rather see though is a `truncateKey` or `truncate: true` option on the column that would specify a column to be truncated. We can also use `string-width` if needed in order to get the screen width for truncation.

**Comment by HaraldNordgren** [comment]
@jdxcode Thanks for the comment!

`heroku releases` already does truncation on the 'description' column (https://github.com/heroku/heroku-apps/pull/216/files#diff-3a33aff60e5d208717c24446df958a82L13) so this is nothing new. It also takes screen width into account.

However, this truncation has a systematic error in that it's always slighty too wide, regardless of terminal width. So by introducing a new concept I figure out a way to do the truncation with better precision.

Of course I would rename variables. But I'm guessing you want something more/better than that :)

**Comment by jdxcode** [comment]
would it be possible to fix this just inside of the release command? My hesitation is that I don't want to include new behavior to the table function. It would have to be replicated in another package and it's already got a couple of bits of functionality that are somewhat duplicated we now have to support without going through a deprecation process—so I want to avoid adding anything new to table if possible.

Alternatively, if I could go back to before all of this I would prefer to change this functionality where we had a truncation key we could specify on the table that would handle this for us. It's hard here though because it's not just a simple truncation, it also has kind of a second column inside of it.

**Comment by HaraldNordgren** [comment]
@jdxcode I think that makes a lot of sense actually.

Closing this PR. Please take a look at the new implementation in https://github.com/heroku/heroku-apps/pull/216

**Pull request closed without merging**
