### PR TITLE
Add streams.{stdout,stderr} for pipe mocking

### PR DESCRIPTION
**Pull request by ransombriggs**
@dickeyxxx could you review?  this is for https://github.com/heroku/heroku-apps/pull/164 so that we can just pipe to something that we can also mock out for testing.  not married to the name / implementation, just threw something together quick

### CODE REVIEW

**Comment by ransombriggs** [comment]
@dickeyxxx technically I could overwrite `process.stdout._write` but opted for this because I do not want to patch internals because it would probably do bad things to test output, etc.

**Comment by dickeyxxx** [comment]
hmm will this won't work with things like console.log right? Maybe it would be preferable to use std-mocks?

**Comment by ransombriggs** [comment]
@dickeyxxx it will not work with `console.log` but I am fine with that, as I do not want to actually change how any native node methods behave when users want the cli output to be mocked out.  In addition to fearing unintended side effects of changing global, I also use `console.log` when debugging tests sometimes :(

**Comment by dickeyxxx** [comment]
I think std-mocks would be better than this

**Comment by ransombriggs** [comment]
I was able to use `std-mocks` to test the piping, closing

**Pull request closed without merging**
