### PR TITLE
prepend warnings with WARNING:

### PR DESCRIPTION
**Pull request by dickeyxxx**
otherwise only color differentiates from errors

thoughts @ransombriggs?

### CODE REVIEW

**Comment by ransombriggs** [comment]
LGTM: let me know when you ship this so I can update heroku-apps dependency

**Comment by ransombriggs** [comment]
Now that I have thought about this three seconds longer, what would you think of adding ERROR: to the error messages as well?

**Comment by dickeyxxx** [comment]
I'm against putting it on errors. We show errors all the time for validation errors and simple things like that. I think it would be really noisy. This is just to differentiate.

Why would you want to bump the release though just for this?

**Comment by ransombriggs** [comment]
Because heroku-apps warning output would be inconsistent with other plugins that require the most recent version.

**Pull request merged**
