### PR TITLE
added table

### PR DESCRIPTION
**Pull request by dickeyxxx**
thoughts @bjeanes? It's a direct port from your code

### CODE REVIEW

**Comment by dickeyxxx** [comment]
@bjeanes actually check out the last commit, I made a change needed to use more than 1 part of a row in a column cell

**Comment by bjeanes** [comment]
I'll check again on Monday. I think it's fine but I had one API change I really wanted to make re: the column width calculation and I want to check my notes to see if it's worth doing before this gets merged.

**Comment by dickeyxxx** [comment]
any update @bjeanes? I'd like to get this out to push the ps command

**Comment by bjeanes** [comment]
Go ahead. I won't have time to look at this, but I can always change the API later and we bump the version a bit higher to show it

**Comment by dickeyxxx** [comment]
yeah if it's just column width stuff I don't think it will cause any problems to add it in

**Pull request merged**
