### PR TITLE
disable mask when not tty or term=dumb

### PR DESCRIPTION
**Pull request by dickeyxxx**

### CODE REVIEW

**Comment by dickeyxxx** [comment]
fixes https://github.com/heroku/cli/issues/294#issuecomment-228399149

cc @uhoh-itsmaciek

**Comment by uhoh-itsmaciek** [comment]
It works =D 💖💖💖💖💖

**Comment by dickeyxxx** [comment]
yayyy

**Comment by ransombriggs** [comment]
@dickeyxxx Sorry for the late response, but does anything besides 2fa use options.mask or options.hide ?  Having characters show up on terminals like cygwin seems like unexpected behaviors for users of this library.

**Comment by dickeyxxx** [comment]
but in those cases we can't hide the input anyways, right?

**Comment by ransombriggs** [comment]
@dickeyxxx I would expect this to fail if it cannot mask or hide rather than exposing, I cannot think of how this would be a problem right now, but if we end up using this for login, I think this would be pretty bad.

**Comment by uhoh-itsmaciek** [comment]
For what it's worth, `passwd` works (and hides input) in emacs' `M-x shell`, so it should be possible to get this to work.

**Comment by dickeyxxx** [comment]
@uhoh-itsmaciek I can probably still depend on stdin raw mode even if TTY=dumb actually. The real problem is what to do in cygwin, but that's still an unsolved problem.

@ransombriggs I think you're right here. I'll test the stdin raw mode in emacs and see if it still works.

**Pull request merged**
